# Text-to-Python Code Generation Recipe
#
# Converted from: docs/assets/recipes/code_generation/text_to_python.py
#
# Generates Python code based on natural language instructions with quality scoring.
# Use model_alias: nvidia-text (or your preferred model alias)

columns:
  - name: industry_sector
    column_type: sampler
    sampler_type: category
    params:
      values:
        - Healthcare
        - Finance
        - Technology

  - name: topic
    column_type: sampler
    sampler_type: subcategory
    params:
      category: industry_sector
      values:
        Healthcare:
          - Electronic Health Records (EHR) Systems
          - Telemedicine Platforms
          - AI-Powered Diagnostic Tools
        Finance:
          - Fraud Detection Software
          - Automated Trading Systems
          - Personal Finance Apps
        Technology:
          - Cloud Computing Platforms
          - Artificial Intelligence and Machine Learning Platforms
          - DevOps and CI/CD Tools

  - name: code_complexity
    column_type: sampler
    sampler_type: category
    params:
      values:
        - Beginner
        - Intermediate
        - Advanced

  - name: code_concept
    column_type: sampler
    sampler_type: subcategory
    params:
      category: code_complexity
      values:
        Beginner:
          - Variables
          - Data Types
          - Functions
          - Loops
          - Classes
        Intermediate:
          - List Comprehensions
          - Object-oriented programming
          - Lambda Functions
          - Web frameworks
          - Pandas
        Advanced:
          - Multithreading
          - Context Managers
          - Generators

  - name: instruction_phrase
    column_type: sampler
    sampler_type: category
    params:
      values:
        - Write a function that
        - Create a class that
        - Implement a script
        - Can you create a function
        - Develop a module that

  - name: instruction
    column_type: llm-text
    model_alias: nvidia-text
    system_prompt: You are an expert at generating clear and specific programming tasks.
    prompt: |
      Generate an instruction to create Python code that solves a specific problem.
      The instruction should begin with the following phrase: "{{ instruction_phrase }}".

      Important Guidelines:
      * Industry Relevance: Ensure the instruction pertains to the {{ industry_sector }} sector and {{ topic }} topic.
      * Code Complexity: Tailor the instruction to the {{ code_complexity }} level. Utilize relevant {{ code_concept }} where appropriate to match the complexity level.
      * Clarity and Specificity: Make the problem statement clear and unambiguous. Provide sufficient context to understand the requirements without being overly verbose.
      * Response Formatting: Do not include any markers such as ### Response ### in the instruction.

  - name: code_implementation
    column_type: llm-code
    model_alias: nvidia-text
    code_lang: python
    system_prompt: You are an expert Python programmer who writes clean, efficient, and well-documented code.
    prompt: |
      Write Python code for the following instruction:
      Instruction: {{ instruction }}

      Important Guidelines:
      * Code Quality: Your code should be clean, complete, self-contained, and accurate.
      * Code Validity: Please ensure that your Python code is executable and does not contain any errors.
      * Packages: Remember to import any necessary libraries, and to use all libraries you import.
      * Complexity & Concepts: The code should be written at a {{ code_complexity }} level, making use of concepts such as {{ code_concept }}.

  - name: code_judge_result
    column_type: llm-judge
    model_alias: nvidia-text
    prompt: |
      You are an expert in Python programming, with specialized knowledge in software engineering, data science, and algorithmic problem-solving.

      You think about potential flaws and errors in the code. You are a tough critic, but a fair one.

      Take a deep breath and use the Python Code Quality Rubric below to score the **Generated Python Code** based on the INSTRUCTIONS.

      #### INSTRUCTIONS
      The Generated Python Code should be a valid response to the Natural Language Prompt below

      Natural Language Prompt:
      {{ instruction }}

      Generated Python Code
      {{ code_implementation }}
    scores:
      - name: Relevance
        description: Adherence to INSTRUCTIONS and CONTEXT
        options:
          4: Perfectly meets all specified requirements.
          3: Meets most requirements with minor deviations.
          2: Moderate deviation from the instructions.
          1: Significant deviations from the instructions.
          0: Does not adhere to the instructions.

      - name: Pythonic
        description: "Pythonic Code and Best Practices (Does the code follow Python conventions and best practices?)"
        options:
          4: "The code exemplifies Pythonic principles, making excellent use of Python-specific constructs, standard library modules and programming idioms; follows all relevant PEPs."
          3: "The code closely follows Python conventions and adheres to many best practices; good use of Python-specific constructs, standard library modules and programming idioms."
          2: "The code generally follows Python conventions but has room for better alignment with Pythonic practices."
          1: "The code loosely follows Python conventions, with several deviations from best practices."
          0: "The code does not follow Python conventions or best practices, using non-Pythonic approaches."

      - name: Readability
        description: "Readability and Maintainability (Is the Python code easy to understand and maintain?)"
        options:
          4: "The code is excellently formatted, follows PEP 8 guidelines, is elegantly concise and clear, uses meaningful variable names, ensuring high readability and ease of maintenance; organizes complex logic well. Docstrings are given in a Google Docstring format."
          3: "The code is well-formatted in the sense of code-as-documentation, making it relatively easy to understand and maintain; uses descriptive names and organizes logic clearly."
          2: "The code is somewhat readable with basic formatting and some comments, but improvements are needed; needs better use of descriptive names and organization."
          1: "The code has minimal formatting, making it hard to understand; lacks meaningful names and organization."
          0: "The code is unreadable, with no attempt at formatting or description."

      - name: Efficiency
        description: "Efficiency and Performance (Is the code optimized for performance?)"
        options:
          4: "The solution is highly efficient, using appropriate data structures and algorithms; avoids unnecessary computations and optimizes for both time and space complexity."
          3: "The solution is efficient, with good use of Python's built-in functions and libraries; minor areas for optimization."
          2: "The solution is moderately efficient, but misses some opportunities for optimization; uses some inefficient patterns."
          1: "The solution shows poor efficiency, with notable performance issues; lacks effective optimization techniques."
          0: "The solution is highly inefficient; overlooks fundamental optimization practices, resulting in significant performance issues."

  - name: code_validity_result
    column_type: validation
    validator_type: code
    target_columns:
      - code_implementation
    validator_params:
      code_lang: python
    batch_size: 100
